rm -rf frames/*.xyz
rm -rf seed.out
rm -rf config.final
rm -rf measures/instant_energy.out
rm -rf measures/instant_pressure.out
rm -rf averages/output.epot.0
rm -rf averages/output.pres.0
rm -rf averages/output.gofr.0
rm -rf averages/output.gave.0
