rm -rf averages/*epot.*
rm -rf averages/*ekin.*
rm -rf averages/*etot.*
rm -rf averages/*temp.*
rm -rf averages/*pres.*
rm -rf averages/*gave.*
rm -rf averages/*gofr.*
rm -rf measures/*epot.*
rm -rf measures/*ekin.*
rm -rf measures/*etot.*
rm -rf measures/*temp.*
rm -rf measures/*pres.*
rm -rf frames/*.xyz
rm -rf *.o
rm -rf MolDyn_NVE.exe
